### PR TITLE
Fix for fix for issue #151

### LINKED ISSUE #151: "ValueError: zero-size array to reduction operation minimum which has no identity" with no leafs
Hi, I think I might by accident tracked an error related to #115 and #144, please see below:

Using the current master branch on Win 10 64 bits and Python 2.7.14

```
import numpy as np
import matplotlib.pyplot as plt

from hdbscan import HDBSCAN


# Generate data
test_data = np.array([
    [0.0, 0.0],
    [1.0, 1.0],
    [0.8, 1.0],
    [1.0, 0.8],
    [0.8, 0.8]])

# HDBSCAN
np.random.seed(1)
hdb_unweighted = HDBSCAN(min_cluster_size=3, gen_min_span_tree=True, allow_single_cluster=True)
hdb_unweighted.fit(test_data)

fig = plt.figure()
cd = hdb_unweighted.condensed_tree_
cd.plot()
fig.suptitle('Unweighted HDBSCAN condensed tree plot'); plt.show()
```

Whole traceback ("anonymised"):

```
Traceback (most recent call last):
  File "...\JetBrains\PyCharm 2017.2.4\helpers\pydev\pydev_run_in_console.py", line 37, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File ".../.PyCharm2017.3/config/scratches/scratch_2.py", line 22, in <module>
    cd.plot()
  File "build\bdist.win-amd64\egg\hdbscan\plots.py", line 321, in plot
    max_rectangle_per_icicle=max_rectangles_per_icicle)
  File "build\bdist.win-amd64\egg\hdbscan\plots.py", line 104, in get_plot_data
    leaves = _get_leaves(self._raw_tree)
  File "build\bdist.win-amd64\egg\hdbscan\plots.py", line 44, in _get_leaves
    root = cluster_tree['parent'].min()
  File "C:\ProgramData\Anaconda3\envs\venv_temp_hdbscan_dev_py27\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

I have tracked down the problem to lines 42-45 of `plots.py`:
```
def _get_leaves(condensed_tree):
    cluster_tree = condensed_tree[condensed_tree['child_size'] > 1]
    root = cluster_tree['parent'].min()
    return _recurse_leaf_dfs(cluster_tree, root)
```
`cluster_tree` created here is empty, so line 44 throws an error.

I am not sure if there is any solution to this except maybe plotting the `single_linkage_tree_`?

### PR DESCRIPTION
**Pull request by m-dz**
Should fix #151 , but I'm struggling with running tests on Win machine (the known "ERROR: Failure: ImportError (No module named _hdbscan_linkage)").

### CODE REVIEW

**Comment by m-dz** [comment]
@lmcinnes , you are not that strict with line lengths I see :)

**Comment by m-dz** [comment]
Well, I can add a test, but first I need to figure out how to run them on Win... I am able to compile and use the module, but when running tests with `python -c "import nose; nose.main()" -v hdbscan` I got the error mentioned above. Any hints?

**Comment by lmcinnes** [comment]
I like PEP8, but the strict line lengths are ... annoying at times. It's still useful to get the report about the other stuff.

**Comment by lmcinnes** [comment]
It looks good, coveralls is just complaining for the sake of it. You can add a test with the plotting tests under ``allow_single_cluster=True``and that should do the job -- if it isn't obvious let me know and I can worry about it another time.

Thanks for the fix!

**Comment by m-dz** [comment]
I will have a look within 2-3 days, won't be able to spend more time on this now I'm afraid.

**Comment by lmcinnes** [comment]
That's fine, I'll just merge this now and I can deal with test later.

**Comment by lmcinnes** [comment]
Thanks again!

**Comment by m-dz** [comment]
No problem, was a pleasure!

**Pull request merged**
