### PR TITLE
[MRG] Address issue #61 - PEP8

### PR DESCRIPTION
**Pull request by glemaitre**
Addressing issue #61

### CODE REVIEW

**Comment by lmcinnes** [comment]
Did you want me to merge this in now, or would you prefer I wait until a few more files have been completed?

**Comment by glemaitre** [comment]
Nop, at the end like this you can squash all commits together. That will be cleaner ;)

**Comment by glemaitre** [comment]
@lmcinnes I finished for the PEP8 checked. You can make a review for merging.

**Comment by lmcinnes** [comment]
Thanks so much for doing this; it is clearly a great deal of work. I generally follow PEP8, but am not a stickler (especially over line lengths as you noticed) and I really appreciate having all of this cleaned up. I'm particularly grateful for the documentation clean-up and consistency!

**Comment by glemaitre** [comment]
No problem ;)

**Pull request merged**
