### PR TITLE
update build

### PR DESCRIPTION
**Pull request by gansanay**
Some propositions and fixes to start preparing for refactoring and integration into scikit-learn:
* use latest version of miniconda
* use latest versions of dependencies numpy, scipy, cython
* build against Python versions from 3.6 through 3.9
* update build script as recommended by anaconda for a smoother readability in Travis logs
* switch from nose to pytest (as in scikit-learn)
* switch from coveralls to codecov (as in scikit-learn) -> @lmcinnes, this will require that you enable the API link at https://codecov.io by signing in and adding the repo
* update `.gitignore` for ignoring `__pycache__` files

I put all the install / test / success scripts into travis.yml, considering it was more readable until more than two code building pipelines are implemented.
Feel free to tell me if you would like to split this update in more steps.

You might still encounter random build errors due to intermittent assertion errors in `test_flat.py` (as described in #420).

### CODE REVIEW

**Comment by gansanay** [comment]
Coverage upload to codecov actually went ok!

**Comment by lmcinnes** [comment]
Thanks -- this is greatly appreciated. There is some refactoring that has been long-overdue but I really haven't had the opportunity. Getting testing updated and in line with sklearn is a great start. Looking forward to anything else you wish to contribute!

**Comment by gansanay** [comment]
Glad to help! You may now get the codecov badge at https://codecov.io/gh/scikit-learn-contrib/hdbscan/settings/badge if you want to replace the coveralls one in `README.rst`.

Thank you for creating this module! I get interesting results applying umap and then hdbscan on small datasets with many dimensions and variable densities, and your documentation is very well written.

I may have to invest a bit more time before I submit a new PR ;-) I think now I need to read the papers to be able to contribute further. But then I would be glad to help with the refactoring and sklearn integration!

**Comment by gansanay** [comment]
I just saw the invitation for collaborating, thank you! Used these new rights to switch the codecov badge!

**Pull request merged**
