### PR TITLE
Update basic_hdbscan.rst

### PR DESCRIPTION
**Pull request by dmarkos**
Added import statements of the modules used in the tutorial. Also fixed a typo (wach -> each)

### CODE REVIEW

**Comment by lmcinnes** [comment]
Thanks!

**Comment by dmarkos** [comment]
Np. I probably do the same for the rest also.

Στις 12 Ιουλ 2017 3:59 μ.μ., ο χρήστης "Leland McInnes" <
notifications@github.com> έγραψε:

**Comment by lmcinnes** [comment]
Sounds great! Let me know if you would like push access to update the docs as you see fit.

**Comment by dmarkos** [comment]
Hello again. Anything you want to point out for the docs now that I am
tidying them up? Do you think the order of the documents on the sidebar is
ok? What do you want to be covered in the documents?

Since I am trying to familiarize myself with the library it will take
double the time to finish, but I want to do it. So far I am liking the
library and I have a dataset that I want to test hdbscan on (spoiler alert
is textual data). So running along with the documents will be beneficial.

Cheers

PS: Push access would be sweet. Does that mean no more pull requests?

2017-07-12 18:19 GMT+03:00 Leland McInnes <notifications@github.com>:

**Comment by lmcinnes** [comment]
The order of things in the tutorial is a little arbitrary -- if you want to make it make more sense fora new user that would be good. It also lacks anything on robust single linkage clustering, which might be beneficial. Also the material that discusses the various trees that can be output and things that can be done with them is lighter than perhaps it could be. I wasn't sure what someone new to the code would want to know -- so if you find anything to add to that I would certainly appreciate it. Finally there is the FAQ which could certainly be improved with more questions and more answers.

If you are doing document clustering I would be interested to know what you are using for document embedding. HDBSCAN* doesn't work well on high dimensional data so, for example, a pure TFIDF matrix would not work well as input -- you would want to dimension reduce it first. I am working with some colleagues on a new document embedding algorithm, so if you're interested in experimental code I can ping you when we actually have something you can try.

Finally, yes, we can skip PRs now, although I would prefer to be consulted on code changes (at least for now). If it is documentation, go ahead and make the changes as needed.

**Comment by dmarkos** [comment]
Hello,

> The order of things in the tutorial is a little arbitrary -- if you want
> to make it make more sense fora new user that would be good.
>
I will surely give it a try. The tutorial needs some simplification and a
regular transition from topic to topic, and of course to be concise (every
aspect needs to be presented).

> It also lacks anything on robust single linkage clustering, which might be
> beneficial. Also the material that discusses the various trees that can be
> output and things that can be done with them is lighter than perhaps it
> could be.
>
I will have to look into those topics some more.

> I wasn't sure what someone new to the code would want to know -- so if you
> find anything to add to that I would certainly appreciate it. Finally there
> is the FAQ which could certainly be improved with more questions and more
> answers.
>
I will maybe follow other clustering tutorials and maybe see what they are
covering and port that stuff to hdbscan.

> If you are doing document clustering I would be interested to know what
> you are using for document embedding. HDBSCAN* doesn't work well on high
> dimensional data so, for example, a pure TFIDF matrix would not work well
> as input
>
Oh! That's no bueno. I am using a TFIDF which is for 100+k (documents) per
10k (terms). But I am meaning to reduce it by filtering out words based on
their frequency etc. What do you mean that HDBSCAN* doesn't work well. How
are the results? I haven't tried it yet, but I am planning to.

> -- you would want to dimension reduce it first.
>
I want to try topic modeling for a small number of topics, and maybe
word2vec (or doc2vec). Also I did reduce the documents into 2 dimensions,
but it was done mainly for visualization purposes. I haven't thought to
cluster that matrix, but maybe I will give it a try.

> I am working with some colleagues on a new document embedding algorithm,
> so if you're interested in experimental code I can ping you when we
> actually have something you can try.
>
Sure. Happy to help :)

> Finally, yes, we can skip PRs now, although I would prefer to be consulted
> on code changes (at least for now). If it is documentation, go ahead and
> make the changes as needed.
>
Of course. I don't mean to make changes on the code base.

Great talking to you man. Have a nice one.


Cheers

>

**Pull request merged**
