### PR TITLE
fix issue-436 unused deprecated joblib option

### PR DESCRIPTION
**Pull request by neontty**
fix issue-436

joblib feature deprecated in joblib release 1.0.0 was causing crash

### CODE REVIEW

**Comment by neontty** [comment]
note: CI failing is pre-existing and unrelated to this fix

**Comment by redafekry** [comment]
TypeError: __init__() got an unexpected keyword argument 'check_pickle'
how to solve ?!!

**Comment by kevin-balkoski-enview** [comment]
> TypeError: **init**() got an unexpected keyword argument 'check_pickle'
> how to solve ?!!

Until this fix is merged, install joblib 0.17:
pip:
```pip install joblib==0.17.0```
or conda:
```conda install joblib==0.17.0```

**Comment by lmcinnes** [comment]
Looks good to me.

**Comment by neontty** [comment]
> Until this fix is merged, install joblib 0.17:

fix is merged? do you mean new release version?

**Comment by lmcinnes** [comment]
I need to put together a new release for other reasons anyway, so hopefully that can be resolved soon as well.

**Comment by jinhyunglee** [comment]
hi, can I ask when the new release version will be available?

**Comment by balazsrobi** [comment]
I'm also interested when should we expect the new release version which includes this fix? @lmcinnes
The suggested joblib downgrade also caused other issues for me. Does installation via github solves this? @neontty 
Thanks for help in advance!

**Comment by neontty** [comment]
@balazsrobi, yes. If you download the git repo and use it to build the wheel, then that will allow you to install the fixed version of hdbscan.

**Pull request merged**
